gpu: nvgpu: Remove unused function
When compiling NVGPU with the GCC option '-Wmissing-prototypes' the
following error is observed ...

 nvgpu/drivers/gpu/nvgpu/os/linux/nvlink.c:42:5:
  error: no previous prototype for nvgpu_nvlink_train
  [-Werror=missing-prototypes]
   | int nvgpu_nvlink_train(struct gk20a *g, u32 link_id, bool from_off)
   |     ^~~~~~~~~~~~~~~~~~

The function nvgpu_nvlink_train() is no longer used and has not been
used for a long time. Therefore, fix the above by removing this legacy
function.

Bug 4404965

Change-Id: Ib5d13b024a072d20cb569cfa77a86a74274d3fe7
Signed-off-by: Jon Hunter <jonathanh@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvgpu/+/3029179
(cherry picked from commit e378ca55059fdf649d3300ae98ba80ac6262c893)
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvgpu/+/3035510
Reviewed-by: Alex Waterman <alexw@nvidia.com>
GVS: Gerrit_Virtual_Submit <buildbot_gerritrpt@nvidia.com>